In [1]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 1550, 4.464], 
  [-10.0, 1850, 4.464], 
  [10.0, 1550, 4.464], 
  [10.0, 1850, 4.464], 
  [30.0, 1550, 4.464], 
  [30.0, 1850, 4.464], 
  [-10.0, 1550, 6.696], 
  [-10.0, 1850, 6.696], 
  [10.0, 1550, 6.696], 
  [10.0, 1850, 6.696], 
  [30.0, 1550, 6.696], 
  [30.0, 1850, 6.696], 
  [-10.0, 1550, 8.928], 
  [-10.0, 1850, 8.928],   
  [10.0, 1550, 8.928], 
  [10.0, 1850, 8.928], 
  [30.0, 1550, 8.928], 
  [30.0, 1850, 8.928]]


#Part 1 output data: VL (V) and Power out (W)
ydata = [[26.1, 152.8], 
 [26.5, 172.7], 
 [27.9, 191.4], 
 [28.3, 198.0], 
 [29.6, 217.8], 
 [30.1, 224.4],  
 [26.9, 118.8], 
 [27.2, 122.1], 
 [28.8, 136.4], 
 [29.1, 139.7], 
 [30.6, 154.0], 
 [31.0, 158.4],  
 [27.3, 92.4], 
 [27.6, 94.6], 
 [29.2, 105.6], 
 [29.6, 107.8], 
 [31.1, 119.9], 
 [31.5, 123.2]]


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

[[-10.0, 1550, 4.464], [-10.0, 1850, 4.464], [10.0, 1550, 4.464], [10.0, 1850, 4.464], [30.0, 1550, 4.464], [30.0, 1850, 4.464], [-10.0, 1550, 6.696], [-10.0, 1850, 6.696], [10.0, 1550, 6.696], [10.0, 1850, 6.696], [30.0, 1550, 6.696], [30.0, 1850, 6.696], [-10.0, 1550, 8.928], [-10.0, 1850, 8.928], [10.0, 1550, 8.928], [10.0, 1850, 8.928], [30.0, 1550, 8.928], [30.0, 1850, 8.928]]
[[ -10.    1550.       4.464]
 [ -10.    1850.       4.464]
 [  10.    1550.       4.464]
 [  10.    1850.       4.464]
 [  30.    1550.       4.464]
 [  30.    1850.       4.464]
 [ -10.    1550.       6.696]
 [ -10.    1850.       6.696]
 [  10.    1550.       6.696]
 [  10.    1850.       6.696]
 [  30.    1550.       6.696]
 [  30.    1850.       6.696]
 [ -10.    1550.       8.928]
 [ -10.    1850.       8.928]
 [  10.    1550.       8.928]
 [  10.    1850.       8.928]
 [  30.    1550.       8.928]
 [  30.    1850.       8.928]]
[[26.1, 152.8], [26.5, 172.7], [27.9, 191.4], [28.3, 198.0], [29.6, 217.8]

In [4]:
import numpy as np

In [7]:
Tamed=np.median(xarray[:,0])
IDmed=np.median(xarray[:,1])
RLmed=np.median(xarray[:,2])
VLmed=np.median(yarray[:,0])
Wdmed=np.median(yarray[:,1])

Xmedian = [Tamed,IDmed,RLmed]
Ymedian = [VLmed,Wdmed]
print(Xmedian)
print(Ymedian)

[10.0, 1700.0, 6.696]
[28.950000000000003, 138.05]


## normalize the data by dividing each parameter value by its median value

In [8]:
Xtask2=xarray/Xmedian
Ytask2=yarray/Ymedian
print(Xtask2)
print(Ytask2)

[[-1.          0.91176471  0.66666667]
 [-1.          1.08823529  0.66666667]
 [ 1.          0.91176471  0.66666667]
 [ 1.          1.08823529  0.66666667]
 [ 3.          0.91176471  0.66666667]
 [ 3.          1.08823529  0.66666667]
 [-1.          0.91176471  1.        ]
 [-1.          1.08823529  1.        ]
 [ 1.          0.91176471  1.        ]
 [ 1.          1.08823529  1.        ]
 [ 3.          0.91176471  1.        ]
 [ 3.          1.08823529  1.        ]
 [-1.          0.91176471  1.33333333]
 [-1.          1.08823529  1.33333333]
 [ 1.          0.91176471  1.33333333]
 [ 1.          1.08823529  1.33333333]
 [ 3.          0.91176471  1.33333333]
 [ 3.          1.08823529  1.33333333]]
[[0.9015544  1.10684535]
 [0.91537133 1.25099602]
 [0.96373057 1.38645418]
 [0.9775475  1.43426295]
 [1.0224525  1.57768924]
 [1.03972366 1.62549801]
 [0.92918826 0.86055777]
 [0.93955095 0.88446215]
 [0.99481865 0.98804781]
 [1.00518135 1.01195219]
 [1.05699482 1.11553785]
 [1.07081174 1.1474103

## (b)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Xtask2, Ytask2, test_size=1/3)

##  (c)

In [10]:
#2.4
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the follwoing 2 lines are only needed for Mac OS machines
import os
from keras import backend as K
#initialize weights with values between -0.2 and 1.2
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)

model = keras.Sequential([
    keras.layers.Dense(6, activation=K.elu, input_shape=[3],  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(16, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(2,  kernel_initializer=initializer)
  ])

Using TensorFlow backend.
2021-11-11 17:50:21.382461: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-11 17:50:21.382787: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [11]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation. 
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks. 
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here 
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.

#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.0150)
model.compile(loss='mean_absolute_error',optimizer=rms)

## (d) smallest lose要小于0.025

In [12]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training. 
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again. 
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs 
#I found acceptable prediction accuracy.

#The fit method takes three parameters; namely, x, y, and number of epochs. 
#During model training, if all the batches of data are seen by the model once, 
#we say that one epoch has been completed.

# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
    monitor='loss', 
    mode='min', 
    patience = 100, 
    restore_best_weights = True, 
    verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss', 
                     mode='min',  verbose=1, save_best_only=True)

#historyData = model.fit(xarray,yarray,epochs=500,callbacks=[es])
historyData = model.fit(X_train,Y_train,epochs=400,callbacks=[es]) 

loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))

Epoch 1/400
12/12 [==============================] - 1s 95ms/step - loss: 0.6468
Epoch 2/400
12/12 [==============================] - 0s 556us/step - loss: 0.6164
Epoch 3/400
12/12 [==============================] - 0s 598us/step - loss: 0.8167
Epoch 4/400
12/12 [==============================] - 0s 666us/step - loss: 0.6506
Epoch 5/400
12/12 [==============================] - 0s 1ms/step - loss: 0.3932
Epoch 6/400
12/12 [==============================] - 0s 1ms/step - loss: 0.2055
Epoch 7/400
12/12 [==============================] - 0s 746us/step - loss: 0.2089
Epoch 8/400
12/12 [==============================] - 0s 2ms/step - loss: 0.3011
Epoch 9/400
12/12 [==============================] - 0s 723us/step - loss: 0.1932
Epoch 10/400
12/12 [==============================] - 0s 839us/step - loss: 0.2586
Epoch 11/400
12/12 [==============================] - 0s 1ms/step - loss: 0.2405
Epoch 12/400
12/12 [==============================] - 0s 763us/step - loss: 0.2953
Epoch 13/400
12/12 [==

Epoch 101/400
12/12 [==============================] - 0s 330us/step - loss: 0.0569
Epoch 102/400
12/12 [==============================] - 0s 269us/step - loss: 0.1072
Epoch 103/400
12/12 [==============================] - 0s 312us/step - loss: 0.1702
Epoch 104/400
12/12 [==============================] - 0s 330us/step - loss: 0.1209
Epoch 105/400
12/12 [==============================] - 0s 294us/step - loss: 0.0916
Epoch 106/400
12/12 [==============================] - 0s 401us/step - loss: 0.0648
Epoch 107/400
12/12 [==============================] - 0s 315us/step - loss: 0.0883
Epoch 108/400
12/12 [==============================] - 0s 332us/step - loss: 0.0866
Epoch 109/400
12/12 [==============================] - 0s 344us/step - loss: 0.2335
Epoch 110/400
12/12 [==============================] - 0s 337us/step - loss: 0.0809
Epoch 111/400
12/12 [==============================] - 0s 310us/step - loss: 0.0362
Epoch 112/400
12/12 [==============================] - 0s 322us/step - loss:

Epoch 199/400
12/12 [==============================] - 0s 333us/step - loss: 0.0413
Epoch 200/400
12/12 [==============================] - 0s 414us/step - loss: 0.0970
Epoch 201/400
12/12 [==============================] - 0s 320us/step - loss: 0.0655
Epoch 202/400
12/12 [==============================] - 0s 365us/step - loss: 0.2118
Epoch 203/400
12/12 [==============================] - 0s 343us/step - loss: 0.0961
Epoch 204/400
12/12 [==============================] - 0s 224us/step - loss: 0.0568
Epoch 205/400
12/12 [==============================] - 0s 273us/step - loss: 0.0851
Epoch 206/400
12/12 [==============================] - 0s 261us/step - loss: 0.0823
Epoch 207/400
12/12 [==============================] - 0s 253us/step - loss: 0.0486
Epoch 208/400
12/12 [==============================] - 0s 246us/step - loss: 0.0658
Epoch 209/400
12/12 [==============================] - 0s 382us/step - loss: 0.0646
Epoch 210/400
12/12 [==============================] - 0s 382us/step - loss:

Epoch 297/400
12/12 [==============================] - 0s 467us/step - loss: 0.0695
Epoch 298/400
12/12 [==============================] - 0s 591us/step - loss: 0.0455
Epoch 299/400
12/12 [==============================] - 0s 677us/step - loss: 0.0507
Epoch 300/400
12/12 [==============================] - 0s 615us/step - loss: 0.0511
Epoch 301/400
12/12 [==============================] - 0s 553us/step - loss: 0.0586
Epoch 302/400
12/12 [==============================] - 0s 505us/step - loss: 0.0672
Epoch 303/400
12/12 [==============================] - 0s 741us/step - loss: 0.1134
Epoch 304/400
12/12 [==============================] - 0s 631us/step - loss: 0.0618
Epoch 305/400
12/12 [==============================] - 0s 560us/step - loss: 0.0558
Epoch 306/400
12/12 [==============================] - 0s 1ms/step - loss: 0.0743
Epoch 307/400
12/12 [==============================] - 0s 891us/step - loss: 0.0827
Epoch 308/400
12/12 [==============================] - 0s 819us/step - loss: 0

# (e)

In [16]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)
    outpt = model.predict(testarray)
    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', outpt[0][0]*VLmed,\
           ', predicted power= ', outpt[0][1]*Wdmed)



row [0] data:  T1=  -10.0 , gam=  870.5882352941176 , qsol=  6.696 , voltage_to_load=  24.851122625215886 , power=  88.53466135458166 ,  predicted voltage_to_load =  24.773911076784135 , predicted power=  81.86267946958542
row [0] data:  T1=  -10.0 , gam=  870.5882352941176 , qsol=  8.928 , voltage_to_load=  25.216580310880826 , power=  68.59442231075697 ,  predicted voltage_to_load =  25.527489101886747 , predicted power=  62.53010231256485
row [0] data:  T1=  30.0 , gam=  729.4117647058823 , qsol=  6.696 , voltage_to_load=  27.957512953367875 , power=  111.66533864541832 ,  predicted voltage_to_load =  27.85775817632675 , predicted power=  98.01353523135185
row [0] data:  T1=  -10.0 , gam=  729.4117647058823 , qsol=  6.696 , voltage_to_load=  24.57702936096718 , power=  86.1418326693227 ,  predicted voltage_to_load =  24.885073113441468 , predicted power=  77.19779433012008
row [0] data:  T1=  30.0 , gam=  870.5882352941176 , qsol=  4.464 , voltage_to_load=  27.500690846286698 , powe

# (f)

In [18]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)

    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed ,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', Y_test[0][0]*VLmed,\
           ', predicted power= ', Y_test[0][1]*Wdmed)

row [0] data:  T1=  -10.0 , gam=  870.5882352941176 , qsol=  6.696 , voltage_to_load=  24.851122625215886 , power=  88.53466135458166 ,  predicted voltage_to_load =  26.587046632124352 , predicted power=  101.29641434262945
row [0] data:  T1=  -10.0 , gam=  870.5882352941176 , qsol=  8.928 , voltage_to_load=  25.216580310880826 , power=  68.59442231075697 ,  predicted voltage_to_load =  26.587046632124352 , predicted power=  101.29641434262945
row [0] data:  T1=  30.0 , gam=  729.4117647058823 , qsol=  6.696 , voltage_to_load=  27.957512953367875 , power=  111.66533864541832 ,  predicted voltage_to_load =  26.587046632124352 , predicted power=  101.29641434262945
row [0] data:  T1=  -10.0 , gam=  729.4117647058823 , qsol=  6.696 , voltage_to_load=  24.57702936096718 , power=  86.1418326693227 ,  predicted voltage_to_load =  26.587046632124352 , predicted power=  101.29641434262945
row [0] data:  T1=  30.0 , gam=  870.5882352941176 , qsol=  4.464 , voltage_to_load=  27.500690846286698 ,