In [3]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 350, 4.464], 
  [-10.0, 650, 4.464], 
  [-10.0, 950, 4.464], 
  [-10.0, 1250, 4.464], 
  [10.0, 350, 4.464], 
  [10.0, 650, 4.464], 
  [10.0, 950, 4.464], 
  [10.0, 1250, 4.464], 
  [30.0, 350, 4.464], 
  [30.0, 650, 4.464], 
  [30.0, 950, 4.464], 
  [30.0, 1250, 4.464], 
  [-10.0, 350, 6.696], 
  [-10.0, 650, 6.696], 
  [-10.0, 950, 6.696], 
  [-10.0, 1250, 6.696], 
  [10.0, 350, 6.696], 
  [10.0, 650, 6.696], 
  [10.0, 950, 6.696], 
  [10.0, 1250, 6.696], 
  [30.0, 350, 6.696], 
  [30.0, 650, 6.696], 
  [30.0, 950, 6.696], 
  [30.0, 1250, 6.696], 
  [-10.0, 350, 8.928], 
  [-10.0, 650, 8.928], 
  [-10.0, 950, 8.928], 
  [-10.0, 1250, 8.928], 
  [10.0, 350, 8.928], 
  [10.0, 650, 8.928], 
  [10.0, 950, 8.928], 
  [10.0, 1250, 8.928], 
  [30.0, 350, 8.928], 
  [30.0, 650, 8.928], 
  [30.0, 950, 8.928], 
  [30.0, 1250, 8.928]] 


#Part 1 output data: VL (V) and Power out (W)
ydata = [[18.9, 80.3], 
 [23.5, 124.6], 
 [24.8, 138.6], 
 [25.6, 146.9], 
 [19.2, 83.1], 
 [25.0, 140.5], 
 [26.5, 157.6], 
 [27.3, 167.5],  
 [19.4, 84.7], 
 [26.4, 156.7], 
 [28.1, 177.7], 
 [29.0, 189.4],
 [22.4, 75.2], 
 [24.8, 92.2], 
 [25.8, 99.7], 
 [26.4, 104.6], 
 [23.6, 83.7], 
 [26.5, 104.9], 
 [27.6, 113.8], 
 [28.3, 119.6], 
 [24.8, 92.0], 
 [28.1, 118.2], 
 [29.3, 128.8], 
 [30.1, 135.5],  
 [23.5, 62.2], 
 [25.4, 72.5], 
 [26.3, 77.6], 
 [26.9, 81.1],  
 [25.0, 70.3], 
 [27.1, 82.7], 
 [28.1, 88.7], 
 [28.7, 92.8],  
 [26.5, 78.6], 
 [28.8, 93.5], 
 [29.9, 100.5], 
 [30.6, 105.2]] 


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

[[-10.0, 350, 4.464], [-10.0, 650, 4.464], [-10.0, 950, 4.464], [-10.0, 1250, 4.464], [10.0, 350, 4.464], [10.0, 650, 4.464], [10.0, 950, 4.464], [10.0, 1250, 4.464], [30.0, 350, 4.464], [30.0, 650, 4.464], [30.0, 950, 4.464], [30.0, 1250, 4.464], [-10.0, 350, 6.696], [-10.0, 650, 6.696], [-10.0, 950, 6.696], [-10.0, 1250, 6.696], [10.0, 350, 6.696], [10.0, 650, 6.696], [10.0, 950, 6.696], [10.0, 1250, 6.696], [30.0, 350, 6.696], [30.0, 650, 6.696], [30.0, 950, 6.696], [30.0, 1250, 6.696], [-10.0, 350, 8.928], [-10.0, 650, 8.928], [-10.0, 950, 8.928], [-10.0, 1250, 8.928], [10.0, 350, 8.928], [10.0, 650, 8.928], [10.0, 950, 8.928], [10.0, 1250, 8.928], [30.0, 350, 8.928], [30.0, 650, 8.928], [30.0, 950, 8.928], [30.0, 1250, 8.928]]
[[ -10.     350.       4.464]
 [ -10.     650.       4.464]
 [ -10.     950.       4.464]
 [ -10.    1250.       4.464]
 [  10.     350.       4.464]
 [  10.     650.       4.464]
 [  10.     950.       4.464]
 [  10.    1250.       4.464]
 [  30.     350.  

In [4]:
import numpy as np

In [6]:
MeanTair= np.mean(xarray[:,0])
MeanID= np.mean(xarray[:,1])
MeanRL= np.mean(xarray[:,2])
Meantotal=[MeanTair,MeanID,MeanRL]
print(Meantotal)                    #求出xarray的mean

[10.0, 800.0, 6.696]


In [7]:
Xstd=np.std(xarray)      #求出xarray的std

In [8]:
xarraynew = (xarray - Meantotal)/Xstd
print(xarraynew)         #新的xarray for task1.1

[[-0.0475569  -1.07003024 -0.00530735]
 [-0.0475569  -0.35667675 -0.00530735]
 [-0.0475569   0.35667675 -0.00530735]
 [-0.0475569   1.07003024 -0.00530735]
 [ 0.         -1.07003024 -0.00530735]
 [ 0.         -0.35667675 -0.00530735]
 [ 0.          0.35667675 -0.00530735]
 [ 0.          1.07003024 -0.00530735]
 [ 0.0475569  -1.07003024 -0.00530735]
 [ 0.0475569  -0.35667675 -0.00530735]
 [ 0.0475569   0.35667675 -0.00530735]
 [ 0.0475569   1.07003024 -0.00530735]
 [-0.0475569  -1.07003024  0.        ]
 [-0.0475569  -0.35667675  0.        ]
 [-0.0475569   0.35667675  0.        ]
 [-0.0475569   1.07003024  0.        ]
 [ 0.         -1.07003024  0.        ]
 [ 0.         -0.35667675  0.        ]
 [ 0.          0.35667675  0.        ]
 [ 0.          1.07003024  0.        ]
 [ 0.0475569  -1.07003024  0.        ]
 [ 0.0475569  -0.35667675  0.        ]
 [ 0.0475569   0.35667675  0.        ]
 [ 0.0475569   1.07003024  0.        ]
 [-0.0475569  -1.07003024  0.00530735]
 [-0.0475569  -0.35667675

In [7]:
#for task 1.2

In [15]:
a=np.median(xarray[:,0])
b=np.median(xarray[:,1])
c=np.median(xarray[:,2])
Xmedian = [a,b,c]
Xmedian

[10.0, 800.0, 6.696]

In [17]:
Xtask2=xarray/Xmedian
Xtask2

array([[-1.        ,  0.4375    ,  0.66666667],
       [-1.        ,  0.8125    ,  0.66666667],
       [-1.        ,  1.1875    ,  0.66666667],
       [-1.        ,  1.5625    ,  0.66666667],
       [ 1.        ,  0.4375    ,  0.66666667],
       [ 1.        ,  0.8125    ,  0.66666667],
       [ 1.        ,  1.1875    ,  0.66666667],
       [ 1.        ,  1.5625    ,  0.66666667],
       [ 3.        ,  0.4375    ,  0.66666667],
       [ 3.        ,  0.8125    ,  0.66666667],
       [ 3.        ,  1.1875    ,  0.66666667],
       [ 3.        ,  1.5625    ,  0.66666667],
       [-1.        ,  0.4375    ,  1.        ],
       [-1.        ,  0.8125    ,  1.        ],
       [-1.        ,  1.1875    ,  1.        ],
       [-1.        ,  1.5625    ,  1.        ],
       [ 1.        ,  0.4375    ,  1.        ],
       [ 1.        ,  0.8125    ,  1.        ],
       [ 1.        ,  1.1875    ,  1.        ],
       [ 1.        ,  1.5625    ,  1.        ],
       [ 3.        ,  0.4375    ,  1.   