In [4]:
#P3pcaExampleF21
#PCA example
import numpy as np
from numpy import linalg as LA
import tensorflow as tf


# replace its data set with the standardized data set created from DS3.1.1LowfluxF21

In [5]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 350, 4.464], 
  [-10.0, 650, 4.464], 
  [-10.0, 950, 4.464], 
  [-10.0, 1250, 4.464], 
  [10.0, 350, 4.464], 
  [10.0, 650, 4.464], 
  [10.0, 950, 4.464], 
  [10.0, 1250, 4.464], 
  [30.0, 350, 4.464], 
  [30.0, 650, 4.464], 
  [30.0, 950, 4.464], 
  [30.0, 1250, 4.464], 
  [-10.0, 350, 6.696], 
  [-10.0, 650, 6.696], 
  [-10.0, 950, 6.696], 
  [-10.0, 1250, 6.696], 
  [10.0, 350, 6.696], 
  [10.0, 650, 6.696], 
  [10.0, 950, 6.696], 
  [10.0, 1250, 6.696], 
  [30.0, 350, 6.696], 
  [30.0, 650, 6.696], 
  [30.0, 950, 6.696], 
  [30.0, 1250, 6.696], 
  [-10.0, 350, 8.928], 
  [-10.0, 650, 8.928], 
  [-10.0, 950, 8.928], 
  [-10.0, 1250, 8.928], 
  [10.0, 350, 8.928], 
  [10.0, 650, 8.928], 
  [10.0, 950, 8.928], 
  [10.0, 1250, 8.928], 
  [30.0, 350, 8.928], 
  [30.0, 650, 8.928], 
  [30.0, 950, 8.928], 
  [30.0, 1250, 8.928]] 

xarray= numpy.array(xdata)

In [7]:
MeanTair= np.mean(xarray[:,0])
MeanID= np.mean(xarray[:,1])
MeanRL= np.mean(xarray[:,2])
Meantotal=[MeanTair,MeanID,MeanRL]
Xstd=np.std(xarray)
X = (xarray - Meantotal)/Xstd
print(X)


[[-0.0475569  -1.07003024 -0.00530735]
 [-0.0475569  -0.35667675 -0.00530735]
 [-0.0475569   0.35667675 -0.00530735]
 [-0.0475569   1.07003024 -0.00530735]
 [ 0.         -1.07003024 -0.00530735]
 [ 0.         -0.35667675 -0.00530735]
 [ 0.          0.35667675 -0.00530735]
 [ 0.          1.07003024 -0.00530735]
 [ 0.0475569  -1.07003024 -0.00530735]
 [ 0.0475569  -0.35667675 -0.00530735]
 [ 0.0475569   0.35667675 -0.00530735]
 [ 0.0475569   1.07003024 -0.00530735]
 [-0.0475569  -1.07003024  0.        ]
 [-0.0475569  -0.35667675  0.        ]
 [-0.0475569   0.35667675  0.        ]
 [-0.0475569   1.07003024  0.        ]
 [ 0.         -1.07003024  0.        ]
 [ 0.         -0.35667675  0.        ]
 [ 0.          0.35667675  0.        ]
 [ 0.          1.07003024  0.        ]
 [ 0.0475569  -1.07003024  0.        ]
 [ 0.0475569  -0.35667675  0.        ]
 [ 0.0475569   0.35667675  0.        ]
 [ 0.0475569   1.07003024  0.        ]
 [-0.0475569  -1.07003024  0.00530735]
 [-0.0475569  -0.35667675

In [8]:
print (X.T)  #print the transpose
Xmean = np.mean(X,0)  # compute mean vector
print (Xmean)

[[-0.0475569  -0.0475569  -0.0475569  -0.0475569   0.          0.
   0.          0.          0.0475569   0.0475569   0.0475569   0.0475569
  -0.0475569  -0.0475569  -0.0475569  -0.0475569   0.          0.
   0.          0.          0.0475569   0.0475569   0.0475569   0.0475569
  -0.0475569  -0.0475569  -0.0475569  -0.0475569   0.          0.
   0.          0.          0.0475569   0.0475569   0.0475569   0.0475569 ]
 [-1.07003024 -0.35667675  0.35667675  1.07003024 -1.07003024 -0.35667675
   0.35667675  1.07003024 -1.07003024 -0.35667675  0.35667675  1.07003024
  -1.07003024 -0.35667675  0.35667675  1.07003024 -1.07003024 -0.35667675
   0.35667675  1.07003024 -1.07003024 -0.35667675  0.35667675  1.07003024
  -1.07003024 -0.35667675  0.35667675  1.07003024 -1.07003024 -0.35667675
   0.35667675  1.07003024 -1.07003024 -0.35667675  0.35667675  1.07003024]
 [-0.00530735 -0.00530735 -0.00530735 -0.00530735 -0.00530735 -0.00530735
  -0.00530735 -0.00530735 -0.00530735 -0.00530735 -0.00530735 

In [9]:
C = np.cov(X.T)  #transpose is matrix we want to work with - compute covariance matrix
print (C)

[[ 1.55085167e-03 -2.36453278e-19 -1.12282950e-21]
 [-2.36453278e-19  6.54265548e-01  7.27558863e-20]
 [-1.12282950e-21  7.27558863e-20  1.93151752e-05]]


In [10]:
w, v = LA.eig(C)  # get the eigenvalues w and the eigenvectors 
print (w)
print (v)

[1.55085167e-03 6.54265548e-01 1.93151752e-05]
[[ 1.00000000e+00  3.62261305e-19  7.33139239e-19]
 [ 0.00000000e+00 -1.00000000e+00 -1.69800206e-19]
 [ 0.00000000e+00 -8.32671227e-19  1.00000000e+00]]


In [12]:
A  = np.array([v[:,2],v[:,1]])  # form the transformation matrix using eigenvectors
# for the top two eigenvalues
print(A)

[[ 7.33139239e-19 -1.69800206e-19  1.00000000e+00]
 [ 3.62261305e-19 -1.00000000e+00 -8.32671227e-19]]


In [13]:
Y = np.matmul(A,(X-Xmean).T) # Apply transformation to obtain new   
                             # data representation in 2-D
print(Y)

[[-5.30734998e-03 -5.30734998e-03 -5.30734998e-03 -5.30734998e-03
  -5.30734998e-03 -5.30734998e-03 -5.30734998e-03 -5.30734998e-03
  -5.30734998e-03 -5.30734998e-03 -5.30734998e-03 -5.30734998e-03
  -7.68722976e-19 -8.89850545e-19 -1.01097812e-18 -1.13210568e-18
  -7.33857147e-19 -8.54984716e-19 -9.76112286e-19 -1.09723986e-18
  -6.98991318e-19 -8.20118887e-19 -9.41246457e-19 -1.06237403e-18
   5.30734998e-03  5.30734998e-03  5.30734998e-03  5.30734998e-03
   5.30734998e-03  5.30734998e-03  5.30734998e-03  5.30734998e-03
   5.30734998e-03  5.30734998e-03  5.30734998e-03  5.30734998e-03]
 [ 1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.07003024e+00  3.56676746e-01 -3.56676746e-01 -1.07003024e+00
   1.0700

In [30]:
xhat = np.matmul(A.T,Y).T + Xmean  #recover the original data using the inverse transform
print(xhat)

[[7.07495606 3.92443193 2.99101016]
 [4.35818659 0.63888882 7.95704095]
 [6.18905239 2.80940399 4.97732603]
 [8.45730172 5.53896441 0.94515359]
 [8.31521059 4.68221571 6.96219527]
 [6.43642293 2.56817868 9.06759253]
 [5.56335682 2.43204338 2.93243389]
 [8.88184769 5.11911702 8.01417058]
 [7.19307301 3.80535054 4.97684382]
 [6.53059219 3.48140552 2.17623319]]


In [31]:
mse = np.sum((X - xhat)**2)/10  #mean squared error
print(mse)

0.6749353375153229
