In [1]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 350, 4.464], 
  [-10.0, 650, 4.464], 
  [-10.0, 950, 4.464], 
  [-10.0, 1250, 4.464], 
  [10.0, 350, 4.464], 
  [10.0, 650, 4.464], 
  [10.0, 950, 4.464], 
  [10.0, 1250, 4.464], 
  [30.0, 350, 4.464], 
  [30.0, 650, 4.464], 
  [30.0, 950, 4.464], 
  [30.0, 1250, 4.464], 
  [-10.0, 350, 6.696], 
  [-10.0, 650, 6.696], 
  [-10.0, 950, 6.696], 
  [-10.0, 1250, 6.696], 
  [10.0, 350, 6.696], 
  [10.0, 650, 6.696], 
  [10.0, 950, 6.696], 
  [10.0, 1250, 6.696], 
  [30.0, 350, 6.696], 
  [30.0, 650, 6.696], 
  [30.0, 950, 6.696], 
  [30.0, 1250, 6.696], 
  [-10.0, 350, 8.928], 
  [-10.0, 650, 8.928], 
  [-10.0, 950, 8.928], 
  [-10.0, 1250, 8.928], 
  [10.0, 350, 8.928], 
  [10.0, 650, 8.928], 
  [10.0, 950, 8.928], 
  [10.0, 1250, 8.928], 
  [30.0, 350, 8.928], 
  [30.0, 650, 8.928], 
  [30.0, 950, 8.928], 
  [30.0, 1250, 8.928]] 


#Part 1 output data: VL (V) and Power out (W)
ydata = [[18.9, 80.3], 
 [23.5, 124.6], 
 [24.8, 138.6], 
 [25.6, 146.9], 
 [19.2, 83.1], 
 [25.0, 140.5], 
 [26.5, 157.6], 
 [27.3, 167.5],  
 [19.4, 84.7], 
 [26.4, 156.7], 
 [28.1, 177.7], 
 [29.0, 189.4],
 [22.4, 75.2], 
 [24.8, 92.2], 
 [25.8, 99.7], 
 [26.4, 104.6], 
 [23.6, 83.7], 
 [26.5, 104.9], 
 [27.6, 113.8], 
 [28.3, 119.6], 
 [24.8, 92.0], 
 [28.1, 118.2], 
 [29.3, 128.8], 
 [30.1, 135.5],  
 [23.5, 62.2], 
 [25.4, 72.5], 
 [26.3, 77.6], 
 [26.9, 81.1],  
 [25.0, 70.3], 
 [27.1, 82.7], 
 [28.1, 88.7], 
 [28.7, 92.8],  
 [26.5, 78.6], 
 [28.8, 93.5], 
 [29.9, 100.5], 
 [30.6, 105.2]] 


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

[[-10.0, 350, 4.464], [-10.0, 650, 4.464], [-10.0, 950, 4.464], [-10.0, 1250, 4.464], [10.0, 350, 4.464], [10.0, 650, 4.464], [10.0, 950, 4.464], [10.0, 1250, 4.464], [30.0, 350, 4.464], [30.0, 650, 4.464], [30.0, 950, 4.464], [30.0, 1250, 4.464], [-10.0, 350, 6.696], [-10.0, 650, 6.696], [-10.0, 950, 6.696], [-10.0, 1250, 6.696], [10.0, 350, 6.696], [10.0, 650, 6.696], [10.0, 950, 6.696], [10.0, 1250, 6.696], [30.0, 350, 6.696], [30.0, 650, 6.696], [30.0, 950, 6.696], [30.0, 1250, 6.696], [-10.0, 350, 8.928], [-10.0, 650, 8.928], [-10.0, 950, 8.928], [-10.0, 1250, 8.928], [10.0, 350, 8.928], [10.0, 650, 8.928], [10.0, 950, 8.928], [10.0, 1250, 8.928], [30.0, 350, 8.928], [30.0, 650, 8.928], [30.0, 950, 8.928], [30.0, 1250, 8.928]]
[[ -10.     350.       4.464]
 [ -10.     650.       4.464]
 [ -10.     950.       4.464]
 [ -10.    1250.       4.464]
 [  10.     350.       4.464]
 [  10.     650.       4.464]
 [  10.     950.       4.464]
 [  10.    1250.       4.464]
 [  30.     350.  

In [2]:
import numpy as np

In [3]:
ax=np.median(xarray[:,0])
ay=np.median(yarray[:,0])
bx=np.median(xarray[:,1])
by=np.median(yarray[:,1])
cx=np.median(xarray[:,2])
Xmedian = [ax,bx,cx]
Ymedian = [ay,by]
print(Xmedian)
print(Ymedian)

[10.0, 800.0, 6.696]
[26.45, 100.1]


## normalize the data by dividing each parameter value by its median value

In [4]:
Xtask2=xarray/Xmedian
Ytask2=yarray/Ymedian
print(Xtask2)
print(Ytask2)

[[-1.          0.4375      0.66666667]
 [-1.          0.8125      0.66666667]
 [-1.          1.1875      0.66666667]
 [-1.          1.5625      0.66666667]
 [ 1.          0.4375      0.66666667]
 [ 1.          0.8125      0.66666667]
 [ 1.          1.1875      0.66666667]
 [ 1.          1.5625      0.66666667]
 [ 3.          0.4375      0.66666667]
 [ 3.          0.8125      0.66666667]
 [ 3.          1.1875      0.66666667]
 [ 3.          1.5625      0.66666667]
 [-1.          0.4375      1.        ]
 [-1.          0.8125      1.        ]
 [-1.          1.1875      1.        ]
 [-1.          1.5625      1.        ]
 [ 1.          0.4375      1.        ]
 [ 1.          0.8125      1.        ]
 [ 1.          1.1875      1.        ]
 [ 1.          1.5625      1.        ]
 [ 3.          0.4375      1.        ]
 [ 3.          0.8125      1.        ]
 [ 3.          1.1875      1.        ]
 [ 3.          1.5625      1.        ]
 [-1.          0.4375      1.33333333]
 [-1.          0.8125    

## (b)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Xtask2, Ytask2, test_size=1/3)

##  (c)

In [6]:
#2.4
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the follwoing 2 lines are only needed for Mac OS machines
import os
from keras import backend as K
#initialize weights with values between -0.2 and 1.2
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)

model = keras.Sequential([
    keras.layers.Dense(6, activation=K.elu, input_shape=[3],  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(16, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(2,  kernel_initializer=initializer)
  ])

Using TensorFlow backend.
2021-11-11 16:49:54.802620: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-11 16:49:54.803209: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [7]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation. 
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks. 
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here 
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.

#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.0150)
model.compile(loss='mean_absolute_error',optimizer=rms)

## (d) smallest lose要小于0.025

In [15]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training. 
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again. 
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs 
#I found acceptable prediction accuracy.

#The fit method takes three parameters; namely, x, y, and number of epochs. 
#During model training, if all the batches of data are seen by the model once, 
#we say that one epoch has been completed.

# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
    monitor='loss', 
    mode='min', 
    patience = 100, 
    restore_best_weights = True, 
    verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss', 
                     mode='min',  verbose=1, save_best_only=True)

#historyData = model.fit(xarray,yarray,epochs=500,callbacks=[es])
historyData = model.fit(X_train,Y_train,epochs=400,callbacks=[es]) 

loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))

Epoch 1/400
24/24 [==============================] - 0s 360us/step - loss: 0.0895
Epoch 2/400
24/24 [==============================] - 0s 266us/step - loss: 0.0486
Epoch 3/400
24/24 [==============================] - 0s 158us/step - loss: 0.0518
Epoch 4/400
24/24 [==============================] - 0s 260us/step - loss: 0.0814
Epoch 5/400
24/24 [==============================] - 0s 299us/step - loss: 0.0733
Epoch 6/400
24/24 [==============================] - 0s 674us/step - loss: 0.0527
Epoch 7/400
24/24 [==============================] - 0s 349us/step - loss: 0.0934
Epoch 8/400
24/24 [==============================] - 0s 593us/step - loss: 0.0781
Epoch 9/400
24/24 [==============================] - 0s 663us/step - loss: 0.1144
Epoch 10/400
24/24 [==============================] - 0s 416us/step - loss: 0.0907
Epoch 11/400
24/24 [==============================] - 0s 343us/step - loss: 0.0738
Epoch 12/400
24/24 [==============================] - 0s 323us/step - loss: 0.0922
Epoch 13/400


Epoch 100/400
24/24 [==============================] - 0s 251us/step - loss: 0.0644
Epoch 101/400
24/24 [==============================] - 0s 282us/step - loss: 0.0849
Epoch 102/400
24/24 [==============================] - 0s 306us/step - loss: 0.0661
Epoch 103/400
24/24 [==============================] - 0s 247us/step - loss: 0.0883
Epoch 104/400
24/24 [==============================] - 0s 574us/step - loss: 0.0547
Epoch 105/400
24/24 [==============================] - 0s 455us/step - loss: 0.0591
Epoch 106/400
24/24 [==============================] - 0s 192us/step - loss: 0.0943
Epoch 107/400
24/24 [==============================] - 0s 356us/step - loss: 0.1099
Epoch 108/400
24/24 [==============================] - 0s 522us/step - loss: 0.0480
Epoch 109/400
24/24 [==============================] - 0s 410us/step - loss: 0.0616
Epoch 110/400
24/24 [==============================] - 0s 157us/step - loss: 0.0854
Epoch 111/400
24/24 [==============================] - 0s 364us/step - loss:

Epoch 198/400
24/24 [==============================] - 0s 392us/step - loss: 0.0944
Epoch 199/400
24/24 [==============================] - 0s 250us/step - loss: 0.0566
Epoch 200/400
24/24 [==============================] - 0s 231us/step - loss: 0.0584
Epoch 201/400
24/24 [==============================] - 0s 213us/step - loss: 0.0575
Epoch 202/400
24/24 [==============================] - 0s 321us/step - loss: 0.0742
Epoch 203/400
24/24 [==============================] - 0s 346us/step - loss: 0.0511
Epoch 204/400
24/24 [==============================] - 0s 539us/step - loss: 0.0606
Epoch 205/400
24/24 [==============================] - 0s 175us/step - loss: 0.0496
Epoch 206/400
24/24 [==============================] - 0s 164us/step - loss: 0.0495
Epoch 207/400
24/24 [==============================] - 0s 394us/step - loss: 0.1046
Epoch 208/400
24/24 [==============================] - 0s 268us/step - loss: 0.0958
Epoch 209/400
24/24 [==============================] - 0s 232us/step - loss:

Epoch 296/400
24/24 [==============================] - 0s 317us/step - loss: 0.0437
Epoch 297/400
24/24 [==============================] - 0s 333us/step - loss: 0.0798
Epoch 298/400
24/24 [==============================] - 0s 514us/step - loss: 0.0513
Epoch 299/400
24/24 [==============================] - 0s 366us/step - loss: 0.0485
Epoch 300/400
24/24 [==============================] - 0s 355us/step - loss: 0.0730
Epoch 301/400
24/24 [==============================] - 0s 151us/step - loss: 0.0781
Epoch 302/400
24/24 [==============================] - 0s 170us/step - loss: 0.0733
Epoch 303/400
24/24 [==============================] - 0s 183us/step - loss: 0.0864
Epoch 304/400
24/24 [==============================] - 0s 160us/step - loss: 0.0752
Epoch 305/400
24/24 [==============================] - 0s 166us/step - loss: 0.0548
Epoch 306/400
24/24 [==============================] - 0s 333us/step - loss: 0.0727
Epoch 307/400
24/24 [==============================] - 0s 170us/step - loss:

# (e)

In [33]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)
    outpt = model.predict(testarray)
    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', outpt[0][0]*VLmed,\
           ', predicted power= ', outpt[0][1]*Wdmed)



row [0] data:  T1=  10.0 , gam=  350.0 , qsol=  4.464 , voltage_to_load=  19.2 , power=  83.1 ,  predicted voltage_to_load =  21.637829959392548 , predicted power=  99.81179780960082
row [0] data:  T1=  30.0 , gam=  1250.0 , qsol=  4.464 , voltage_to_load=  29.0 , power=  189.4 ,  predicted voltage_to_load =  31.290964019298553 , predicted power=  211.09411916732788
row [0] data:  T1=  30.0 , gam=  950.0 , qsol=  6.696 , voltage_to_load=  29.300000000000004 , power=  128.8 ,  predicted voltage_to_load =  29.65025587081909 , predicted power=  146.61701726913452
row [0] data:  T1=  10.0 , gam=  650.0 , qsol=  4.464 , voltage_to_load=  25.0 , power=  140.5 ,  predicted voltage_to_load =  24.813680946826935 , predicted power=  130.75886834859847
row [0] data:  T1=  10.0 , gam=  350.0 , qsol=  8.928 , voltage_to_load=  25.0 , power=  70.3 ,  predicted voltage_to_load =  24.341101190447805 , predicted power=  71.41076785326004
row [0] data:  T1=  30.0 , gam=  950.0 , qsol=  8.928 , voltage_t

# (f)

In [31]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)

    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', Y_test[0][0]*VLmed,\
           ', predicted power= ', Y_test[0][1]*Wdmed)

row [0] data:  T1=  10.0 , gam=  350.0 , qsol=  4.464 , voltage_to_load=  19.2 , power=  83.1 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  30.0 , gam=  1250.0 , qsol=  4.464 , voltage_to_load=  29.0 , power=  189.4 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  30.0 , gam=  950.0 , qsol=  6.696 , voltage_to_load=  29.300000000000004 , power=  128.8 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  10.0 , gam=  650.0 , qsol=  4.464 , voltage_to_load=  25.0 , power=  140.5 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  10.0 , gam=  350.0 , qsol=  8.928 , voltage_to_load=  25.0 , power=  70.3 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  30.0 , gam=  950.0 , qsol=  8.928 , voltage_to_load=  29.9 , power=  100.5 ,  predicted voltage_to_load =  28.3 , predicted power=  119.6
row [0] data:  T1=  -10.0 , gam=  1250.