In [1]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 350, 4.464], 
  [-10.0, 650, 4.464], 
  [-10.0, 950, 4.464], 
  [-10.0, 1250, 4.464], 
  [10.0, 350, 4.464], 
  [10.0, 650, 4.464], 
  [10.0, 950, 4.464], 
  [10.0, 1250, 4.464], 
  [30.0, 350, 4.464], 
  [30.0, 650, 4.464], 
  [30.0, 950, 4.464], 
  [30.0, 1250, 4.464], 
  [-10.0, 350, 6.696], 
  [-10.0, 650, 6.696], 
  [-10.0, 950, 6.696], 
  [-10.0, 1250, 6.696], 
  [10.0, 350, 6.696], 
  [10.0, 650, 6.696], 
  [10.0, 950, 6.696], 
  [10.0, 1250, 6.696], 
  [30.0, 350, 6.696], 
  [30.0, 650, 6.696], 
  [30.0, 950, 6.696], 
  [30.0, 1250, 6.696], 
  [-10.0, 350, 8.928], 
  [-10.0, 650, 8.928], 
  [-10.0, 950, 8.928], 
  [-10.0, 1250, 8.928], 
  [10.0, 350, 8.928], 
  [10.0, 650, 8.928], 
  [10.0, 950, 8.928], 
  [10.0, 1250, 8.928], 
  [30.0, 350, 8.928], 
  [30.0, 650, 8.928], 
  [30.0, 950, 8.928], 
  [30.0, 1250, 8.928]] 


#Part 1 output data: VL (V) and Power out (W)
ydata = [[18.9, 80.3], 
 [23.5, 124.6], 
 [24.8, 138.6], 
 [25.6, 146.9], 
 [19.2, 83.1], 
 [25.0, 140.5], 
 [26.5, 157.6], 
 [27.3, 167.5],  
 [19.4, 84.7], 
 [26.4, 156.7], 
 [28.1, 177.7], 
 [29.0, 189.4],
 [22.4, 75.2], 
 [24.8, 92.2], 
 [25.8, 99.7], 
 [26.4, 104.6], 
 [23.6, 83.7], 
 [26.5, 104.9], 
 [27.6, 113.8], 
 [28.3, 119.6], 
 [24.8, 92.0], 
 [28.1, 118.2], 
 [29.3, 128.8], 
 [30.1, 135.5],  
 [23.5, 62.2], 
 [25.4, 72.5], 
 [26.3, 77.6], 
 [26.9, 81.1],  
 [25.0, 70.3], 
 [27.1, 82.7], 
 [28.1, 88.7], 
 [28.7, 92.8],  
 [26.5, 78.6], 
 [28.8, 93.5], 
 [29.9, 100.5], 
 [30.6, 105.2]] 


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

[[-10.0, 350, 4.464], [-10.0, 650, 4.464], [-10.0, 950, 4.464], [-10.0, 1250, 4.464], [10.0, 350, 4.464], [10.0, 650, 4.464], [10.0, 950, 4.464], [10.0, 1250, 4.464], [30.0, 350, 4.464], [30.0, 650, 4.464], [30.0, 950, 4.464], [30.0, 1250, 4.464], [-10.0, 350, 6.696], [-10.0, 650, 6.696], [-10.0, 950, 6.696], [-10.0, 1250, 6.696], [10.0, 350, 6.696], [10.0, 650, 6.696], [10.0, 950, 6.696], [10.0, 1250, 6.696], [30.0, 350, 6.696], [30.0, 650, 6.696], [30.0, 950, 6.696], [30.0, 1250, 6.696], [-10.0, 350, 8.928], [-10.0, 650, 8.928], [-10.0, 950, 8.928], [-10.0, 1250, 8.928], [10.0, 350, 8.928], [10.0, 650, 8.928], [10.0, 950, 8.928], [10.0, 1250, 8.928], [30.0, 350, 8.928], [30.0, 650, 8.928], [30.0, 950, 8.928], [30.0, 1250, 8.928]]
[[ -10.     350.       4.464]
 [ -10.     650.       4.464]
 [ -10.     950.       4.464]
 [ -10.    1250.       4.464]
 [  10.     350.       4.464]
 [  10.     650.       4.464]
 [  10.     950.       4.464]
 [  10.    1250.       4.464]
 [  30.     350.  

In [2]:
import numpy as np

In [3]:
ax=np.median(xarray[:,0])
ay=np.median(yarray[:,0])
bx=np.median(xarray[:,1])
by=np.median(yarray[:,1])
cx=np.median(xarray[:,2])
Xmedian = [ax,bx,cx]
Ymedian = [ay,by]
print(Xmedian)
print(Ymedian)

[10.0, 800.0, 6.696]
[26.45, 100.1]


## normalize the data by dividing each parameter value by its median value

In [4]:
Xtask2=xarray/Xmedian
Ytask2=yarray/Ymedian
print(Xtask2)
print(Ytask2)

[[-1.          0.4375      0.66666667]
 [-1.          0.8125      0.66666667]
 [-1.          1.1875      0.66666667]
 [-1.          1.5625      0.66666667]
 [ 1.          0.4375      0.66666667]
 [ 1.          0.8125      0.66666667]
 [ 1.          1.1875      0.66666667]
 [ 1.          1.5625      0.66666667]
 [ 3.          0.4375      0.66666667]
 [ 3.          0.8125      0.66666667]
 [ 3.          1.1875      0.66666667]
 [ 3.          1.5625      0.66666667]
 [-1.          0.4375      1.        ]
 [-1.          0.8125      1.        ]
 [-1.          1.1875      1.        ]
 [-1.          1.5625      1.        ]
 [ 1.          0.4375      1.        ]
 [ 1.          0.8125      1.        ]
 [ 1.          1.1875      1.        ]
 [ 1.          1.5625      1.        ]
 [ 3.          0.4375      1.        ]
 [ 3.          0.8125      1.        ]
 [ 3.          1.1875      1.        ]
 [ 3.          1.5625      1.        ]
 [-1.          0.4375      1.33333333]
 [-1.          0.8125    

## (b)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Xtask2, Ytask2, test_size=1/3)

##  (c)

In [6]:
#2.4
import keras
import pandas as pd
from keras.models import Sequential
import numpy as np
import keras.backend as kb
import tensorflow as tf
#the follwoing 2 lines are only needed for Mac OS machines
import os
from keras import backend as K
#initialize weights with values between -0.2 and 1.2
initializer = keras.initializers.RandomUniform(minval= -0.2, maxval=0.5)

model = keras.Sequential([
    keras.layers.Dense(6, activation=K.elu, input_shape=[3],  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(12, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(16, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(8, activation=K.elu,  kernel_initializer=initializer),
    keras.layers.Dense(2,  kernel_initializer=initializer)
  ])

Using TensorFlow backend.
2021-11-11 19:22:42.675837: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-11 19:22:42.676164: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [7]:
#We’re using RMSprop as our optimizer here. RMSprop stands for Root Mean Square Propagation. 
#It’s one of the most popular gradient descent optimization algorithms for deep learning networks. 
#RMSprop is an optimizer that’s reliable and fast.
#We’re compiling the mode using the model.compile function. The loss function used here 
#is mean squared error. After the compilation of the model, we’ll use the fit method with ~500 epochs.
#Number of epochs can be varied.

#from tf.keras import optimizers
rms = keras.optimizers.RMSprop(0.0150)
model.compile(loss='mean_absolute_error',optimizer=rms)

## (d) smallest lose要小于0.025

In [8]:
#After the compilation of the model, we’ll use the fit method with 500 epochs.
#I started with epochs value of 100 and then tested the model after training. 
#The prediction was not that good. Then I modified the number of epochs to 200 and tested the model again. 
#Accuracy had improved slightly, but figured I’d give it one more try. Finally, at 500 epochs 
#I found acceptable prediction accuracy.

#The fit method takes three parameters; namely, x, y, and number of epochs. 
#During model training, if all the batches of data are seen by the model once, 
#we say that one epoch has been completed.

# Add an early stopping callback
es = keras.callbacks.EarlyStopping(
    monitor='loss', 
    mode='min', 
    patience = 100, 
    restore_best_weights = True, 
    verbose=1)
# Add a checkpoint where loss is minimum, and save that model
mc = keras.callbacks.ModelCheckpoint('best_model.SB', monitor='loss', 
                     mode='min',  verbose=1, save_best_only=True)

#historyData = model.fit(xarray,yarray,epochs=500,callbacks=[es])
historyData = model.fit(X_train,Y_train,epochs=400,callbacks=[es]) 

loss_hist = historyData.history['loss']
#The above line will return a dictionary, access it's info like this:
best_epoch = np.argmin(historyData.history['loss']) + 1
print ('best epoch = ', best_epoch)
print('smallest loss =', np.min(loss_hist))

Epoch 1/400
24/24 [==============================] - 1s 38ms/step - loss: 0.5252
Epoch 2/400
24/24 [==============================] - 0s 167us/step - loss: 2.9555
Epoch 3/400
24/24 [==============================] - 0s 288us/step - loss: 0.7627
Epoch 4/400
24/24 [==============================] - 0s 191us/step - loss: 0.3518
Epoch 5/400
24/24 [==============================] - 0s 325us/step - loss: 0.2640
Epoch 6/400
24/24 [==============================] - 0s 350us/step - loss: 0.3191
Epoch 7/400
24/24 [==============================] - 0s 533us/step - loss: 0.3777
Epoch 8/400
24/24 [==============================] - 0s 274us/step - loss: 0.4272
Epoch 9/400
24/24 [==============================] - 0s 244us/step - loss: 0.1952
Epoch 10/400
24/24 [==============================] - 0s 503us/step - loss: 0.2205
Epoch 11/400
24/24 [==============================] - 0s 248us/step - loss: 0.2847
Epoch 12/400
24/24 [==============================] - 0s 300us/step - loss: 0.4078
Epoch 13/400
2

Epoch 100/400
24/24 [==============================] - 0s 194us/step - loss: 0.1154
Epoch 101/400
24/24 [==============================] - 0s 207us/step - loss: 0.1419
Epoch 102/400
24/24 [==============================] - 0s 168us/step - loss: 0.1758
Epoch 103/400
24/24 [==============================] - 0s 362us/step - loss: 0.2515
Epoch 104/400
24/24 [==============================] - 0s 324us/step - loss: 0.1677
Epoch 105/400
24/24 [==============================] - 0s 431us/step - loss: 0.0997
Epoch 106/400
24/24 [==============================] - 0s 304us/step - loss: 0.1167
Epoch 107/400
24/24 [==============================] - 0s 189us/step - loss: 0.2206
Epoch 108/400
24/24 [==============================] - 0s 361us/step - loss: 0.1578
Epoch 109/400
24/24 [==============================] - 0s 201us/step - loss: 0.1330
Epoch 110/400
24/24 [==============================] - 0s 169us/step - loss: 0.1636
Epoch 111/400
24/24 [==============================] - 0s 201us/step - loss:

Epoch 198/400
24/24 [==============================] - 0s 214us/step - loss: 0.1828
Epoch 199/400
24/24 [==============================] - 0s 243us/step - loss: 0.1338
Epoch 200/400
24/24 [==============================] - 0s 236us/step - loss: 0.1218
Epoch 201/400
24/24 [==============================] - 0s 326us/step - loss: 0.1463
Epoch 202/400
24/24 [==============================] - 0s 196us/step - loss: 0.0990
Epoch 203/400
24/24 [==============================] - 0s 154us/step - loss: 0.1085
Epoch 204/400
24/24 [==============================] - 0s 243us/step - loss: 0.0888
Epoch 205/400
24/24 [==============================] - 0s 238us/step - loss: 0.1496
Epoch 206/400
24/24 [==============================] - 0s 299us/step - loss: 0.1071
Epoch 207/400
24/24 [==============================] - 0s 282us/step - loss: 0.1204
Epoch 208/400
24/24 [==============================] - 0s 239us/step - loss: 0.1186
Epoch 209/400
24/24 [==============================] - 0s 155us/step - loss:

Epoch 296/400
24/24 [==============================] - 0s 558us/step - loss: 0.0805
Epoch 297/400
24/24 [==============================] - 0s 639us/step - loss: 0.0993
Epoch 298/400
24/24 [==============================] - 0s 348us/step - loss: 0.1352
Epoch 299/400
24/24 [==============================] - 0s 525us/step - loss: 0.1074
Epoch 300/400
24/24 [==============================] - 0s 217us/step - loss: 0.0853
Epoch 301/400
24/24 [==============================] - 0s 248us/step - loss: 0.1316
Epoch 302/400
24/24 [==============================] - 0s 195us/step - loss: 0.1374
Epoch 303/400
24/24 [==============================] - 0s 161us/step - loss: 0.0971
Epoch 304/400
24/24 [==============================] - 0s 168us/step - loss: 0.1124
Epoch 305/400
24/24 [==============================] - 0s 239us/step - loss: 0.1115
Epoch 306/400
24/24 [==============================] - 0s 442us/step - loss: 0.1174
Epoch 307/400
24/24 [==============================] - 0s 543us/step - loss:

Epoch 394/400
24/24 [==============================] - 0s 385us/step - loss: 0.1554
Epoch 395/400
24/24 [==============================] - 0s 172us/step - loss: 0.0846
Epoch 396/400
24/24 [==============================] - 0s 475us/step - loss: 0.0980
Epoch 397/400
24/24 [==============================] - 0s 342us/step - loss: 0.1088
Epoch 398/400
24/24 [==============================] - 0s 170us/step - loss: 0.0795
Epoch 399/400
24/24 [==============================] - 0s 374us/step - loss: 0.0891
Epoch 400/400
24/24 [==============================] - 0s 197us/step - loss: 0.0911
best epoch =  391
smallest loss = 0.06692367047071457


# (e)

In [9]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)
    outpt = model.predict(testarray)
    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', outpt[0][0]*VLmed,\
           ', predicted power= ', outpt[0][1]*Wdmed)



row [0] data:  T1=  -10.0 , gam=  350.0 , qsol=  6.696 , voltage_to_load=  22.4 , power=  75.2 ,  predicted voltage_to_load =  23.530138581991196 , predicted power=  78.51596255898475
row [0] data:  T1=  -10.0 , gam=  1250.0 , qsol=  8.928 , voltage_to_load=  26.9 , power=  81.1 ,  predicted voltage_to_load =  26.131470552086828 , predicted power=  88.68480907678604
row [0] data:  T1=  10.0 , gam=  650.0 , qsol=  6.696 , voltage_to_load=  26.5 , power=  104.9 ,  predicted voltage_to_load =  26.165189650654792 , predicted power=  99.8244466304779
row [0] data:  T1=  30.0 , gam=  1250.0 , qsol=  4.464 , voltage_to_load=  29.0 , power=  189.4 ,  predicted voltage_to_load =  31.31454594731331 , predicted power=  201.3667463302612
row [0] data:  T1=  30.0 , gam=  350.0 , qsol=  8.928 , voltage_to_load=  26.5 , power=  78.6 ,  predicted voltage_to_load =  25.696956422924995 , predicted power=  86.50567379593849
row [0] data:  T1=  -10.0 , gam=  650.0 , qsol=  4.464 , voltage_to_load=  23.5 ,

# (f)

In [10]:
test = []
outpt=[]

Tamed = 10
IDmed = 800.
RLmed = 6.696
VLmed = 26.45
Wdmed = 100.1


#first point (row [0])comparison of data and prediction
# put in a loop to print comparion for all data points
for i in range(len(X_train)):
    
    test = [[ X_train[i][0] , X_train[i][1] , X_train[i][2] ]]
    testarray = np.array(test)

    print ('row [0] data:  T1= ', X_train[i][0]*Tamed, ', gam= ', X_train[i][1]*IDmed, \
        ', qsol= ', X_train[i][2]*RLmed,', voltage_to_load= ', Y_train[i][0]*VLmed,\
        ', power= ', Y_train[i][1]*Wdmed,',  predicted voltage_to_load = ', Y_test[0][0]*VLmed,\
           ', predicted power= ', Y_test[0][1]*Wdmed)

row [0] data:  T1=  -10.0 , gam=  350.0 , qsol=  6.696 , voltage_to_load=  22.4 , power=  75.2 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  -10.0 , gam=  1250.0 , qsol=  8.928 , voltage_to_load=  26.9 , power=  81.1 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  10.0 , gam=  650.0 , qsol=  6.696 , voltage_to_load=  26.5 , power=  104.9 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  30.0 , gam=  1250.0 , qsol=  4.464 , voltage_to_load=  29.0 , power=  189.4 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  30.0 , gam=  350.0 , qsol=  8.928 , voltage_to_load=  26.5 , power=  78.6 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  -10.0 , gam=  650.0 , qsol=  4.464 , voltage_to_load=  23.5 , power=  124.6 ,  predicted voltage_to_load =  27.3 , predicted power=  167.5
row [0] data:  T1=  -10.0 , gam=  950.0 , qsol=  6